### ISSUE TITLE
Unused code.

### ISSUE THREAD

**Issue by burritosss** [NabilCherigui/Carefree#1]
https://github.com/NabilCherigui/Carefree/blob/b3c6ccd417cdef6dcc48a99596615727721c1ed7/Assets/_Scripts/Player/Movement/PlayerMovement.cs#L9

Deze variable wordt nergens gebruikt, omdat je de "direction" variabel in de functie "Move" lokaal verandert.

En gebruik aub niet van deze halve variable namen, dus niet _direc maar gewoon _direction

**Comment by NabilCherigui** [comment]
Update
