### ISSUE TITLE
Code execution order.

### ISSUE THREAD

**Issue by burritosss** [NabilCherigui/Carefree#2]
https://github.com/NabilCherigui/Carefree/blob/b3c6ccd417cdef6dcc48a99596615727721c1ed7/Assets/_Scripts/Player/Movement/PlayerMovement.cs#L15-L18

Zelf vindt ik het handig om alle GetComponents te doen in de "Awake" functie zodat je die components kan gebruiken in de "Start" functie.

**Comment by NabilCherigui** [comment]
Update
