### ISSUE TITLE
Refactoring DRY.

### ISSUE THREAD

**Issue by burritosss** [NabilCherigui/Carefree#3]
https://github.com/NabilCherigui/Carefree/blob/b3c6ccd417cdef6dcc48a99596615727721c1ed7/Assets/_Scripts/Player/Movement/PlayerMovement.cs#L31-L68

DRY = don't repeat yourself.
Deze code is extreem slordig.

Voor een beter voorbeeld: https://gist.github.com/burritosss/1fc59d464d5ff9c6f9081082121a4c45
ref: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator

**Comment by NabilCherigui** [comment]
Update
